# Site settings
title: Juan Alberto Delaroca
email: jad@equiporoca.com
description: > # this means to ignore newlines until "baseurl:"
  Juan Alberto Delaroca is a ethnograpy and marketing professional
  with experience ranging from action sports to food and beverage industry
  and lifestyle apparel.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://juan-a-delaroca.github.io/" # the base hostname & protocol for your site
twitter_username: equiporoca
github_username:  juan-a-delaroca

# Build settings
markdown: kramdown
